### ISSUE TITLE
config options not available

### ISSUE THREAD

**Issue by MattrCoUk** [ogra1/tinyproxy-snap#1]
Cannot change anything in config apart from the opts from the readme.md
eg. user, group, reverseonly etc. not working with sudo snap set tinyproxy-ogra... 

I cannot change anything in the config manually - access denied.

**Comment by ogra1** [comment]
you can change any config option you want (except for user/group, snaps always run as root inside a root-safe confinement so these two options will not have any effect) by editing the config file directly as root:

sudo vi /var/snap/tinyproxy-ogra/current/tinyproxy.conf
sudo snap restart tinyproxy-ogra

the snap set/get options are mainly focused around running this snap pre-configured on a user-less Ubuntu Core system, if you specifically need options on such a setup i'm happy to add them.

**Comment by MattrCoUk** [comment]
I see now that this is possible to change the settings in tinyproxy.conf using vi. 

I haven't tried vi before (since I hate it :-) and it always failed due to Permission denied (eg nano, pinano, or Textmate via Transmit app over ssh) Feel free to close the issue. Thanks for the response!

**Comment by ogra1** [comment]
great, thanks for the reply !
